MatchingTranslations:
  enabled: false

# Disable check for "required" template files
# https://shopify.dev/themes/tools/theme-check/checks/missing-required-template-files
MissingRequiredTemplateFiles:
  enabled: false